version: '3.1'
services:
  db:
    image: mysql/mysql-server
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: develrootpass
      MYSQL_DATABASE: registr
      MYSQL_USER: registr
      MYSQL_PASSWORD: registr
  web:
    build: .
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
